# Generated by Django 4.0.1 on 2022-01-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='fatherland',
            new_name='patronymic',
        ),
    ]
