# Generated by Django 4.0.1 on 2022-01-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('sales', '0002_remove_sale_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
