# Generated by Django 4.0.1 on 2022-01-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_name_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='name_company',
        ),
    ]
